export const CATEGORIES = [
  { name: 'географія', id: 1 },
  { name: 'прийменники', id: 2 },
  { name: 'spell', id: 3 },
  { name: 'sentence', id: 4 },
  { name: 'math', id: 5 },
  { name: 'random word', id: 6 },
  { name: 'Birthday', id: 7 },
  { name: 'Eng --> Ukr', id: 8 },
  { name: 'Days', id: 9 },
  { name: 'Past', id: 10 },
];

export const QUESTIONS = {
  1: [
    'швейцярія',
    'італія',
    'іспанія',
    'німеччина',
    'Бразилія',
    'угорщина',
    'польща',
    'україна',
    'китай',
    'чилі',
    'британія',
    'англія',
    'сша',
    'канада',
    'мексика',
    'індія',
    'японія',
  ],
  2: [
    '__ home',
    '__ school',
    '__ a car',
    'I __',
    'You ___',
    'he __',
    'she __',
    '__ Monday',
    '__ Saturday',
    '__ Sunday',
    '__ Wednesday',
    '__ Friday',
    '__ Tuesday',
    '__ Thursday',
    'I am ____ Ukraine',
  ],
  3: [
    'you',
    'home',
    'have',
    'get up',
    'after',
    'school',
    'he',
    'she',
    'dog',
    'cat',
    'horse',
    'red',
    'blue',
    'green',
    'yellow',
  ],
  4: [
    'Після школи я роблю домашню роботу'
  ],
  5: [],
  6: [
    'після школи',
    'Різдво',
    'наступний',
    'попередній',
    'година',
    'хвилина',
    'рік',
    'ти',
    'Я',
    'маю',
    'собака',
    'кіт',
    'кінь',
    'лев',
    'заробляти гроші',
  ],
  7: [

  ],
  8: [
    'I have 2 dogs',
    'I have 10 cats',
    'I make money',
    'you make money',
    'she makes money',
    'he makes money',
    'you do homework',
    'I do homework',
    'he does homework',
    'she does homework',
    'she does homework',
    'How many dogs do you have',
    'How many dogs do I have',
    'How many cats do you have',
    'How many cats do I have',
    'I am from Ukraine',
    'You are from USA',
    'Where are you from?',
  ],
  9: [
    'Понеділок',
    'Monday',
    'Вівторок',
    'Tuesday',
    'Середа',
    'Wednesday',
    'Четвер',
    'Thursday',
    'П"ятниця',
    'Friday',
    'Субота',
    'Saturday',
    'Неділя',
    'Sunday',
  ],
}
